version: "3.4"
services:
  slack-bot-no-cpf:
    tty: true
    image: "slack-bot-no-cpf"
    stdin_open: true
    build:
      context: .
      target: "development"
    volumes:
      - ".:/src"
    env_file: .env
