version: "3.4"
services:
  safe-chat-slack-bot:
    tty: true
    image: "safe-chat-slack-bot"
    stdin_open: true
    build:
      context: .
      target: "development"
    volumes:
      - ".:/src"
    env_file: .env
